# Generated by Django 5.0.1 on 2024-01-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_profile_beli_ili_chorniy_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Beli_ili_chorniy',
            field=models.CharField(blank=True, choices=[('Ч', 'Ч'), ('Б', 'Б')], max_length=1, null=True),
        ),
    ]
