# Generated by Django 5.0.1 on 2024-01-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_alter_posts_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
